export const GET_PILLERS="PILLERS_ARE_GET";
export const GET_PILLERS_SUSCESS="GET_PILLERS_SUSCESS";

export const GET_CUSTOMER="CUSTOMER_ARE_GET";
export const GET_CUSTOMER_SUSCESS="GET_CUSTOMER_SUSCESS";

export const GET_HEALTHCARE="HEALTHCARE_ARE_GET";
export const GET_HEALTHCARE_SUSCESS="GET_HEALTHCARE_SUSCESS";
