//Blog

export const GET_BLOG_DETAILS = "GET_BLOG_DETAILS";
export const GET_BLOG_DETAILS_SUCCESS = "GET_BLOG_DETAILS_SUCCESS";

//Contact Us

export const GET_CONTACT_DETAIL="GET_CONTACT_DETAIL";


//PORTFOLIO

export const GET_PORTFOLIO_DETAILS = "GET_PORTFOLIO_DETAILS";
export const GET_PORTFOLIO_DETAILS_SUCCESS = "GET_PORTFOLIO_DETAILS_SUCCESS";

//ANOUT US  

export const GET_PILLERS="PILLERS_ARE_GET";
export const GET_PILLERS_SUSCESS="GET_PILLERS_SUSCESS";

export const GET_CUSTOMER="CUSTOMER_ARE_GET";
export const GET_CUSTOMER_SUSCESS="GET_CUSTOMER_SUSCESS";

export const GET_HEALTHCARE="HEALTHCARE_ARE_GET";
export const GET_HEALTHCARE_SUSCESS="GET_HEALTHCARE_SUSCESS";
