//Blog

export const GET_BLOG_DETAILS = "GET_BLOG_DETAILS";
export const GET_BLOG_DETAILS_SUCCESS = "GET_BLOG_DETAILS_SUCCESS";

//Contact Us

export const GET_CONTACT_DETAIL="GET_CONTACT_DETAIL";


//PORTFOLIO

export const GET_PORTFOLIO_DETAILS = "GET_PORTFOLIO_DETAILS";
export const GET_PORTFOLIO_DETAILS_SUCCESS = "GET_PORTFOLIO_DETAILS_SUCCESS";